import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Navbar } from 'react-bootstrap'
import MyNavbar from '@/components/navbar'
import LandingImage from '@/components/LandingImage'
import About from '@/components/About'
import VideoTour from '@/components/VideoTour'
import FacultyCarousel from '@/components/FacultyCarousel'
import Events from '@/components/Events'
import Count from '@/components/Count'
import Students from '@/components/Students'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <MyNavbar/>
       <LandingImage/>
       <About/>
       <VideoTour/>
       <FacultyCarousel/>
       <Events/>
       <Count/>
       <Students/>
    </>
  )
}
